version: "3.9"

services:
  product-service:
    image: juanchogonza98/e-commerce:product-servicev1.0.0
    container_name: product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8081
    restart: unless-stopped

