version: "3.9"

services:
  orders-service:
    image: juanchogonza98/e-commerce:order-service 
    container_name: orders-service
    ports:
      - "8083:8083"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

