version: "3.9"

services:
  payment-service:
    image: juanchogonza98/e-commerce:payment-servicelatest
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8082
    restart: unless-stopped
