version: "3.9"

services:
  # === PRODUCTS SERVICE ===
  products-service:
    image: juanchogonza98/e-commerce:products-servicev1.0.0
    container_name: products-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081

  # === PAYMENTS SERVICE ===
  payments-service:
    image: juanchogonza98/e-commerce:payment-servicelatest
    container_name: payments-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - PRODUCTS_API_URL=http://products-service:8081
    depends_on:
      - products-service

  # === ORDERS SERVICE ===
  orders-service:
    image: juanchogonza98/e-commerce:order-service
    container_name: orders-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - PRODUCTS_API_URL=http://products-service:8081
      - PAYMENTS_API_URL=http://payments-service:8082
    depends_on:
      - products-service
      - payments-service

  # === USERS SERVICE ===
  users-service:
    image: juanchogonza98/e-commerce:users-servicelastest
    container_name: users-service
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084

  # === NOTIFICATIONS SERVICE ===
  notifications-service:
    image: juanchogonza98/e-commerce:notifications-servicelatest
    container_name: notifications-service
    ports:
      - "8000:8000"
    environment:
      - SERVER_PORT=8000
    depends_on:
      - orders-service
