version: "3.9"

services:
  # === PRODUCTS SERVICE ===
  products-service:
    image: juanchogonza98/e-commerce:product-servicev1.0.0
    container_name: products-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
    networks:
      - ecommerce-net

  # === ORDERS SERVICE ===
  orders-service:
    image: juanchogonza98/e-commerce:order-servicelatest
    container_name: orders-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - PRODUCTS_API_URL=http://products-service:8081
      - USERS_API_URL=http://users-service:8084
    depends_on:
      - products-service
      - users-service
    networks:
      - ecommerce-net

  # === PAYMENTS SERVICE ===
  payments-service:
    image: juanchogonza98/e-commerce:payment-service
    container_name: payments-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - ORDERS_API_URL=http://orders-service:8083
    depends_on:
      - orders-service
    networks:
      - ecommerce-net

  # === USERS SERVICE ===
  users-service:
    image: juanchogonza98/e-commerce:users-servicelastest
    container_name: users-service
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
